List<Map<String, List<String>>> phraseTypes = [
  {'essentials': essentials},
  {'travel': travel},
  {'car_taxi': carNTaxi},
  {'medical': medical},
  {'restaurant': restaurant},
  {'store': store},
  {'common_problem': commonProblem},
  {'entertainment': entertainment},
  {'education': education},
  {'sign': sign},
  {'money_payment': monayNPayMent},
  {'sightseeing': sightseeing},
  {'at_the_bar': atTheBar},
];

List<String> essentials = [
  "Hello",
  "Where are you from?",
  "I am from",
  "What's your name?",
  "My name is",
  "How are you?",
  "I'm fine, thank you. And you?",
  "Excuse me",
  "Never mind",
  "How's it going?",
  "How have you been?",
  "What's up?",
  "Nice to meet you!",
  "Long time no see!",
  "How do you do?",
  "How's everything?",
  "How's your day?",
  "It's good to see you!",
  "Take care!",
  "Have a nice day!",
  "Catch you later!",
  "See you soon!",
  "Farewell!",
];

List<String> travel = [
  "Where is the airport?",
  "Where is the subway?",
  "Where is the check-in counter for [airline]?",
  "Do I need to remove my shoes and belt?",
  "Here is my passport",
  "Where is the security checkpoint?",
  "What time does my flight depart?",
  "Is my flight on time?",
  "Where is the departure gate for flight [number]?",
  "Where is the baggage claim area?",
  "My luggage is lost. What should I do?",
  "Is there a baggage storage service here?",
  "How many bags can I check in?",
];

List<String> carNTaxi = [
  "Can you call a taxi for me, please?",
  "Where can I find a taxi?",
  "Is there a taxi stand nearby?",
  "How much does it cost to go to [destination]?",
  "Can you take me to [hotel/airport/landmark]?",
  "I’d like to go to [destination], please.",
  "How long will it take to get there?",
  "Can you wait for me here?",
  "Can you turn on the air conditioning, please?",
  "Could you lower the window, please?",
  "Can you drive a bit slower/faster?",
  "How much is the fare?",
  "Can I have a receipt, please?",
  "Please stop the car.",
  "That seems a bit expensive. Can you make it cheaper?",
  "I'm on a budget. Can you help me out?",
  "Can you lower the fare a bit?",
  "I appreciate your help.",
];

List<String> medical = [
  "I’m not feeling well.",
  "I have a headache/stomachache.",
  "Where is the nearest hospital/clinic/pharmacy?",
  "Can you recommend a good hospital?",
  "I’m having difficulty breathing",
  "I need to go to a pharmacy",
  "I need to go to the hospital",
  "Call an ambulance!",
  "I need help immediately!",
  "I have a cough/cold.",
];

List<String> restaurant = [
  "May I see the menu?",
  "Do you have any available tables?",
  "I’d like to order [dish], please.",
  "I’d like to make a reservation for [number] people.",
  "Do you have a vegetarian/vegan menu?",
  "What do you recommend?",
  "I’d like to order [dish], please.",
  "Can you make it less spicy?",
  "Can we have some more bread, please?",
  "Excuse me, we need some more napkins.",
  "Can you please clear the plates?",
  "This dish is delicious!",
  "Could we have some more water, please?",
  "Can I have the bill, please?",
  "Can I pay in cash?",
  "Do you accept credit cards?",
  "The food was excellent, thank you!",
  "We had a wonderful time, thanks!",
];

List<String> store = [
  "Can you tell me where [store name] is?",
  "How do I get to the food court?",
  "Where are the restrooms?",
  "Can you recommend a good clothing store?",
  "Where is the nearest coffee shop?",
  "Can you recommend a good restaurant here?",
  "Do you offer gift wrapping?",
  "Excuse me, where can I find [item]?",
  "Do you have this in a different size/color?",
  "Is this available in stock?",
  "How much does this cost?",
  "Is this on sale?",
  "Do you have any discounts for [students/seniors/members]?",
  "Can you give me a better price?",
  "Are there any promotions right now?",
  "Is this made of [material]?",
  "Where are the fitting rooms?",
  "Can I pay by credit card?",
  "Can I get a receipt, please?",
  "Can I return or exchange this if needed?",
];

List<String> commonProblem = [
  "This item is damaged. Can I exchange it?",
  "I bought this yesterday, but it doesn’t work.",
  "Can I get a refund?",
  "There’s a missing part in this package.",
  "I’m lost. Can you help me find my way?",
  "My phone battery is dead. Is there a place where I can charge it?",
  "I can’t find my hotel. Can you give me directions?",
  "My credit card isn’t working. Can I pay in cash?",
  "I was charged the wrong amount. Can you check it?",
  "Do you accept foreign currency?",
  "Can you call a taxi for me?",
  "How do I get to the nearest subway station?",
  "I’m not feeling well. Is there a pharmacy nearby?",
  "I need to see a doctor. Where is the nearest clinic?",
  "I have a headache. Do you have any painkillers?",
  "Do you speak English?",
  "Can you write that down for me, please?",
  "I don’t understand. Can you repeat that slowly?",
  "My room is too noisy. Can I change rooms?",
  "The air conditioner isn’t working. Can you fix it?",
  "I need extra towels in my room.",
  "Can I have a late check-out?",
  "I’ve lost my room key. Can I get a new one?",
  "Which bus/train goes to [destination]?",
  "How much is a ticket to [destination]?",
  "Do I need to transfer?",
  "Where is the bus stop/train station?",
  "Is this the right platform for [destination]?",
  "I lost my wallet. Can you help me?",
  "I think I’ve been pickpocketed.",
  "Where is the nearest police station?",
];

List<String> entertainment = [
  "What entertainment options are available here?",
  "Can you recommend a good movie/theater/show?",
  "Is there a concert/event happening tonight?",
  "Where is the nearest cinema?",
  "How can I buy tickets for [event]?",
  "Are there any tickets available for tonight’s show?",
  "Can I book tickets online?",
  "What time does the show start?",
  "Do you offer any group discounts?",
  "Where are our seats?",
  "Can I get some popcorn and a drink?",
  "Is this seat taken?",
  "How long is the show?",
  "Is there an intermission?",
  "Can I take photos during the show?",
  "Where can I buy souvenirs?",
  "There seems to be a mistake with my ticket.",
  "The sound system is not clear. Can it be adjusted?",
  "I can’t see the stage from my seat. Can I change seats?",
  "The show was cancelled. How can I get a refund?",
  "Where can I rent a bicycle/kayak?",
  "Are there any guided tours available?",
  "What are the opening hours of the park/museum?",
  "Is there a place to have a picnic?",
];

List<String> education = [
  "Where is the admissions office?",
  "What courses are available this semester?",
  "Can I get a campus tour?",
  "What are the library hours?",
  "How do I register for classes?",
  "Is there a deadline for registration?",
  "Can I audit this course?",
  "What is the course syllabus?",
  "Can you explain that again, please?",
  "I have a question.",
  "What does this word mean?",
  "Can I go to the restroom?",
  "Where can I buy the textbooks?",
  "Is there an online version of this book?",
  "Are there any recommended readings?",
  "Can I borrow this book from the library?",
  "Can I schedule a meeting with you?",
  "I’m having trouble with this assignment. Can you help me?",
  "What is the grading policy?",
  "Can I get feedback on my essay?",
  "Do you want to study together?",
  "Can you help me with this problem?",
  "Are you in this class too?",
  "What clubs and organizations are there?",
  "How can I join the student council?",
  "Are there any sports teams I can join?",
  "What events are happening on campus?",
];

List<String> sign = [
  "Warning Sign",
  "Stop Sign",
  "Yield Sign",
  "Speed Limit Sign",
  "No Entry Sign",
  "Exit Sign",
  "Entrance Sign",
  "Parking Sign",
  "No Parking Sign",
  "Pedestrian Crossing Sign",
  "Hospital Sign",
  "Restroom Sign",
  "Information Sign",
  "Emergency Exit Sign",
  "Danger Sign",
  "Detour Sign",
  "Construction Sign",
  "Gas Station",
  "Rest Area",
  "Tourist Information",
  "Wi-Fi Zone",
  "School Zone",
  "Bus Stop"
];

List<String> monayNPayMent = [
  "Currency",
  "Banknote",
  "Cash",
  "Credit Card",
  "Debit Card",
  "Price",
  "Cost",
  "Discount",
  "Sale",
  "Special Offer",
  "Coupon",
  "Rebate",
  "Bargain",
  "Affordable",
  "Expensive",
  "Cheap",
  "How much does this cost?",
  "Do you accept credit cards?",
  "Can I pay in cash?",
  "Is there a discount for students/seniors?",
  "Can I get a receipt, please?",
  "Do you offer refunds?",
  "Can I pay in installments?",
  "Is there an extra charge for using a credit card?",
  "Can you break a [larger bill, e.g., \$50 bill]?"
];

List<String> sightseeing = [
  "Landmark",
  "Tourist attraction",
  "Historical site",
  "Museum",
  "Gallery",
  "Monument",
  "Park",
  "Zoo",
  "Aquarium",
  "Botanical garden",
  "Where is the nearest tourist information center?",
  "Can I get a map of the city?",
  "What are the must-see attractions here?",
  "Walking distance",
  "Hop-on hop-off bus"
];

List<String> atTheBar = [
  "Cheers!",
  "Can I see the drink menu?",
  "I'd like to order a drink",
  "Can I have a beer, please?",
  "I'll have a glass of wine.",
  "Can I get a cocktail?",
  "What beers do you have on tap?",
  "What do you recommend?",
  "Can I get a non-alcoholic drink?",
  "I'd like a whiskey on the rocks.",
  "Make it a double.",
  "Keep the change.",
  "Excuse me, bartender.",
  "Can you make a custom cocktail?",
  "Let's grab a drink",
  "What time does the bar close?",
  "Is this seat taken?",
  "Can I get a water, please?"
];
